In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as skl

df = pd.read_csv("Sales_data.csv")
print(df)
df.isnull().sum()

FileNotFoundError: [Errno 2] No such file or directory: 'Sales_data.csv'

In [ ]:




df_subset_15 = df.head(15)
plt.xticks(df_subset_15['Total_Amount'])
plt.yticks(df_subset_15['Quantity'])
plt.plot(df_subset_15['Total_Amount'], df_subset_15['Quantity'], label='Total_Amount vs Quantity', color='Red', linestyle = '-', marker='o')
plt.title("Line graph of Quantity sold and Sales Amount")
plt.xlabel("Total_Amount")
plt.ylabel("Quantity")
plt.grid(True)
plt.legend()
plt.legend(loc='best')

NameError: name 'df' is not defined

## **Topic 3: Tuples (4 Questions)**

---

### **Q11. Create and Print Tuple**

**Description:**

Take `N` integers as input and store them in a tuple, then print the tuple.

We can store `N` Integer in a tuple name `nums`.

Note:

- We can take input from the user using `input()`.
- We can also directly take input as an Integer from the user using `int(input())`.

**For example, Input:**

```

  
nums = (1, 2, 3, 4)

```

**Output:**

```
  
(1, 2, 3, 4)

```

---

In [ ]:
n = int(input("Enter the range of tuple: "))
nums = []

for i in range(1,n+1):
  user_input = int(input(f"{i}: "))
  nums.append(user_input)
print("Your Tuple is: ",tuple(nums) )

Enter the range of tuple: 5
1: 8
2: 16
3: 2
4: 5
5: 100
Your Tuple is:  (8, 16, 2, 5, 100)

### **Q12. Find Element in Tuple**

**Description:**

Check if a given element exists in the tuple.

We can store `n` elements in a tuple name `nums` in order to check specific element which we can store in a variable name `element`.

Note:

- We can take input from the user using `input()`.
- We can also directly take input as an Integer from the user using `int(input())`.

**For example, Input:**

```

  
nums = (10, 20, 30, 40, 50)
element = 30

```

**Output:**

```

  
Element Found

```

---

In [ ]:
n = int(input("Enter the range of tuple: "))
nums = []

for i in range(1,n+1):
  user_input = int(input(f"{i}: "))
  nums.append(user_input)
print("Your Tuple is: ",tuple(nums) )

element = int(input("Enter element to search in Tuple: "))

if element in nums:
  print("Element Found")
else:
  print("Element does not exist in given Tuple.")

Enter the range of tuple: 5
1: 7
2: 9
3: 15
4: 3
5: 12
Your Tuple is:  (7, 9, 15, 3, 12)
Enter element to search in Tuple: 9
Element Found

### **Q13. Tuple Length**

**Description:**

Find the length of a tuple.

We can store tuple as `tups`.

Note:

- We can take input from the user using `input()`.
- We can also directly take input as an Integer from the user using `int(input())`.

**Input:**

```

  
tups = (7, 8, 9)

```

**Output:**

```
  
3

```

---

In [ ]:
nums_str = input("Enter comma separated tuple elements: ")
nums = tuple(map(int, nums_str.split(',')))
print(nums)
print("Length of tuple is: ",len(nums))

Enter comma separated tuple elements: 12,34,56,78,90
(12, 34, 56, 78, 90)
Length of tuple is:  5

### **Q14. Count Occurrences in Tuple**

**Description:**

Count how many times a given number appears in the tuple.

We can store numbers in a tuple `nums` in order to find how many times a specific number appeared in it which we can store in variable name `number`.

Note:

- We can take input from the user using `input()`.
- We can also directly take input as an Integer from the user using `int(input())`.

**Input:**

```

  
nums = (1, 2, 2, 3, 4, 2)
number = 2

```

**Output:**

```
  
3

```

In [1]:
import pandas as pd

# Create a sample DataFrame (replace with your actual data loading)
data = {'salary': [1000, 2000, 1500, 3000, 2500]}
df4 = pd.DataFrame(data)

# Generate a New column name score inside our DataFrame, fill it with the column’s mean.
df4['score'] = df4['salary'].mean()

# Display the updated DataFrame
display(df4)

   salary   score
0    1000  2000.0
1    2000  2000.0
2    1500  2000.0
3    3000  2000.0
4    2500  2000.0

In [3]:
# Assuming 'Sales_data.csv' is available and contains 'Region' and 'Total_Amount' columns
# If not, please replace with the correct file path and column names
try:
    df = pd.read_csv("Sales_data.csv")
except FileNotFoundError:
    print("Error: 'Sales_data.csv' not found. Please upload the file or provide the correct path.")
    # You might want to exit or handle the error appropriately here
    exit()


# Group data by 'Region' and extract 'Total_Amount' for each region
region_data = [df[df['Region'] == r]['Total_Amount'] for r in df['Region'].unique()]

# Create the box plot
plt.boxplot(region_data, labels=df['Region'].unique())
plt.xlabel("Region")
plt.ylabel("Total Amount")
plt.title("Total Amount Spread by Region")
plt.show()

NameError: name 'df' is not defined